# First stage
FROM node:16

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

WORKDIR /home/node/app

COPY package.json ./
COPY yarn.lock ./

RUN yarn --immutable

COPY . .

RUN yarn clean

RUN yarn build