FROM node:16 as base

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

WORKDIR /home/node/app

COPY package.json ./
COPY yarn.lock ./

RUN yarn install --immutable

COPY . .

# Doesn't need an execution line - see docker-compose.yml
