services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: production
    # volumes:
    #   - ./src:/home/node/app/src
    container_name: ts-node-docker-prod
    expose:
      - "4000"
    ports:
      - "4000:4000"
    # command: yarn start Not needed - in dockerfile
