FROM node:16-alpine as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /home/node/app

COPY package.json ./
COPY yarn.lock ./

RUN yarn --immutable

COPY . .

RUN yarn clean

RUN yarn build

CMD ["yarn", "start"]